name: struct
description: Library for packing and unpacking byte data using format strings
repository: https://github.com/davidlawson/struct.dart
version: 3.0.0
dev_dependencies:
  test: '>=1.15.0 <2.0.0'
environment:
  sdk: '>=2.12.0 <3.0.0'